/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PubRouteImport } from './routes/pub'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HqIndexRouteImport } from './routes/hq.index'
import { Route as HqPubIdRouteImport } from './routes/hq.$pubId'
import { Route as ApiPublicTimemotoWebhookRouteImport } from './routes/api/public/timemoto-webhook'

const PubRoute = PubRouteImport.update({
  id: '/pub',
  path: '/pub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HqIndexRoute = HqIndexRouteImport.update({
  id: '/hq/',
  path: '/hq/',
  getParentRoute: () => rootRouteImport,
} as any)
const HqPubIdRoute = HqPubIdRouteImport.update({
  id: '/hq/$pubId',
  path: '/hq/$pubId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTimemotoWebhookRoute =
  ApiPublicTimemotoWebhookRouteImport.update({
    id: '/api/public/timemoto-webhook',
    path: '/api/public/timemoto-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/pub': typeof PubRoute
  '/hq/$pubId': typeof HqPubIdRoute
  '/hq/': typeof HqIndexRoute
  '/api/public/timemoto-webhook': typeof ApiPublicTimemotoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/pub': typeof PubRoute
  '/hq/$pubId': typeof HqPubIdRoute
  '/hq': typeof HqIndexRoute
  '/api/public/timemoto-webhook': typeof ApiPublicTimemotoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/feedback': typeof FeedbackRoute
  '/login': typeof LoginRoute
  '/pub': typeof PubRoute
  '/hq/$pubId': typeof HqPubIdRoute
  '/hq/': typeof HqIndexRoute
  '/api/public/timemoto-webhook': typeof ApiPublicTimemotoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/feedback'
    | '/login'
    | '/pub'
    | '/hq/$pubId'
    | '/hq/'
    | '/api/public/timemoto-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/feedback'
    | '/login'
    | '/pub'
    | '/hq/$pubId'
    | '/hq'
    | '/api/public/timemoto-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/feedback'
    | '/login'
    | '/pub'
    | '/hq/$pubId'
    | '/hq/'
    | '/api/public/timemoto-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  FeedbackRoute: typeof FeedbackRoute
  LoginRoute: typeof LoginRoute
  PubRoute: typeof PubRoute
  HqPubIdRoute: typeof HqPubIdRoute
  HqIndexRoute: typeof HqIndexRoute
  ApiPublicTimemotoWebhookRoute: typeof ApiPublicTimemotoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pub': {
      id: '/pub'
      path: '/pub'
      fullPath: '/pub'
      preLoaderRoute: typeof PubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/': {
      id: '/hq/'
      path: '/hq'
      fullPath: '/hq/'
      preLoaderRoute: typeof HqIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hq/$pubId': {
      id: '/hq/$pubId'
      path: '/hq/$pubId'
      fullPath: '/hq/$pubId'
      preLoaderRoute: typeof HqPubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/timemoto-webhook': {
      id: '/api/public/timemoto-webhook'
      path: '/api/public/timemoto-webhook'
      fullPath: '/api/public/timemoto-webhook'
      preLoaderRoute: typeof ApiPublicTimemotoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  FeedbackRoute: FeedbackRoute,
  LoginRoute: LoginRoute,
  PubRoute: PubRoute,
  HqPubIdRoute: HqPubIdRoute,
  HqIndexRoute: HqIndexRoute,
  ApiPublicTimemotoWebhookRoute: ApiPublicTimemotoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
